"""Guard that the ontology's serializations stay in sync.

The JSON-LD file is the human-edited source; Turtle is the reasoner-canonical
form generated by ``scripts/export_schema_ttl.py``; the Protégé view is the
import-free browsing copy generated by ``scripts/export_protege_view.py``. This
test fails if any two drift — the exact failure mode that left
``tkos-ontology-protege.ttl`` a minor version behind the schema in V2.4.

Comparison uses graph isomorphism (``rdflib.compare.isomorphic``) rather than
raw triple-set equality, because SWRL bodies/heads and ``owl:oneOf`` enums are
RDF lists whose blank nodes get fresh identifiers on each parse; only
structure-aware comparison treats a list and its reserialization as equal.

The hand-written ``tkos-ontology-protege.ttl`` that had drifted to v2.3.0 was
removed (see ADR-0002); only generated serializations now exist, so every copy
is covered here.
"""
from pathlib import Path

from rdflib import Graph, OWL
from rdflib.compare import isomorphic


ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "ontology" / "schema"
VIEWS = ROOT / "ontology" / "views"


def graph_at(path: Path, fmt: str) -> Graph:
    return Graph().parse(path, format=fmt)


def without_imports(graph: Graph) -> Graph:
    # copy-on-write: Graph.remove mutates, so work on a fresh graph of the remainder.
    stripped = Graph()
    for triple in graph:
        if triple[1] != OWL.imports:
            stripped.add(triple)
    return stripped


def main() -> None:
    g_jsonld = graph_at(SCHEMA / "tkos-ontology.jsonld", "json-ld")
    g_ttl = graph_at(SCHEMA / "tkos-ontology.ttl", "turtle")

    # 1. Canonical pair must be isomorphic, imports included.
    if not isomorphic(g_jsonld, g_ttl):
        raise SystemExit(
            "FAIL: JSON-LD and Turtle are not isomorphic. "
            "Regenerate with: python3 scripts/export_schema_ttl.py"
        )
    print(f"jsonld ⇔ ttl: isomorphic ({len(g_jsonld)} triples)")

    # 2. Generated Protégé view must be isomorphic to the source modulo imports
    #    (export_protege_view.py strips imports for browsing).
    g_view = graph_at(VIEWS / "tkos-ontology-protege-view.ttl", "turtle")
    if not isomorphic(without_imports(g_jsonld), g_view):
        raise SystemExit(
            "FAIL: Protégé view drifted from schema. "
            "Regenerate with: python3 scripts/export_protege_view.py"
        )
    print(f"jsonld ⇔ protege-view (modulo imports): isomorphic")


if __name__ == "__main__":
    main()
